- name: Import profile system-wide
  command: cp {{ colour_profile_path }} /usr/share/color/icc/colord/ColorLCD.icc
  args:
    creates: /usr/share/color/icc/colord/ColorLCD.icc
  register: profile_imported

- name: Wait for profile to be imported
  action: command colormgr get-profiles
  register: result
  until: 'result.stdout.find("Profile ID:    icc-8a9627e6323f33eeb2bd566da35e9fc6") != -1'
  retries: 10
  delay: 0.5
  when: profile_imported.changed

- name: Adds colour profile to device
  command: colormgr device-add-profile "xrandr-Apple Computer Inc-Color LCD" "icc-8a9627e6323f33eeb2bd566da35e9fc6"
  when: profile_imported.changed

- name: Makes colour profile default for device
  command: colormgr device-make-profile-default "xrandr-Apple Computer Inc-Color LCD" "icc-8a9627e6323f33eeb2bd566da35e9fc6"
  when: profile_imported.changed
