- name: Create /usr/local/bin folder
  file: state=directory dest="/usr/local/bin"

- name: Copy common toolbox resources
  copy: src=all/ dest=/usr/local/bin mode=755

- name: Copy Fedora-specific toolbox resources
  copy: src=fedora/ dest=/usr/local/bin mode=755
  when: ansible_distribution == "Fedora"

- name: Copy Ubuntu-specific toolbox resources
  copy: src=ubuntu/ dest=/usr/local/bin mode=755
  when: ansible_distribution == "Ubuntu"
