- name: Operating system detection  
  hosts: all
  tasks:
    - name: Dectects Linux distribution
      group_by: key=os_{{ ansible_distribution }}
      changed_when: False

- name: Basic hardware setup - Ubuntu
  hosts: os_Ubuntu
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes cache_valid_time=360
    - apt: name=macfanctld state=latest
    - apt: upgrade=yes
  roles:
    - mbp-hardware/ubuntu/power-management
    - mbp-hardware/ubuntu/keyboard

- name: Basic hardware setup - Fedora
  hosts: os_Fedora
  sudo: yes
  vars:
    fedy:
      - disk_io_scheduler
      - font_rendering
      - media_codecs
      - adobe_flash
      # - dvd_playback
      - sublime_text3
    test:
      test1: test
      test2: testi
  roles:
    - mbp-hardware/fedora/power-management
    - mbp-hardware/all/boot
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/wireless
    - base/fedora/autojump
    - base/fedora/fedy
    - development/fedora/git
