- name: Detect operating system  
  hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}
      changed_when: False

- name: Basic hardware setup - Ubuntu style
  hosts: os_Ubuntu
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes cache_valid_time=360
    - apt: name=macfanctld state=latest
    - apt: upgrade=yes
  roles:
    - mbp-hardware/ubuntu/power-management
    - mbp-hardware/ubuntu/keyboard

- name: Basic hardware setup - Fedora style
  hosts: os_Fedora
  sudo: yes
  roles:
    - mbp-hardware/fedora/power-management
    - mbp-hardware/fedora/keyboard
    - development/fedora/git
