- name: Install VirtualBox dependencies
  dnf: name=kernel-devel

- name: Install VirtualBox package
  dnf: name=VirtualBox

- name: Install VirtualBox akmod
  dnf: name=akmod-VirtualBox

- name: Install VirtualBox and Vagrant packages
  dnf: name=vagrant

- name: Set default vagrant provider to virtualbox
  lineinfile:
    dest: /etc/environment
    line: VAGRANT_DEFAULT_PROVIDER=virtualbox
