- name: Install VirtualBox dependencies
  yum: name=kernel-devel

- name: Install VirtualBox package
  yum: name=VirtualBox

- name: Install VirtualBox akmod
  yum: name=akmod-VirtualBox

- name: Install VirtualBox and Vagrant packages
  yum: name=vagrant

- name: Set default vagrant provider to virtualbox
  lineinfile:
    dest: /etc/environment
    line: VAGRANT_DEFAULT_PROVIDER=virtualbox
