- name: Install VirtualBox dependencies
  yum: name=kernel-devel

- name: Install VirtualBox package
  yum: name=VirtualBox

- name: Install VirtualBox akmod
  yum: name=akmod-VirtualBox

- name: Install VirtualBox and Vagrant packages
  yum: name=vagrant
