# Run as the user you want to install the license for
# Specify the path to the Sublime Text 3 license file on the command line like this:
#   -e secret_path=/path/to/secret

- name: Put the Sublime Text 3 license file in place
  hosts: desktop
  sudo: no
  tasks:
    - name: Create the Sublime Text 3 config folder
      file: state=directory dest={{ ansible_env['HOME'] }}/.config/sublime-text-3/Local mode=700

    - name: Copy license file
      copy: src={{ secret_path }} dest={{ ansible_env['HOME'] }}/.config/sublime-text-3/Local/License.sublime_license mode=600
