- name: Enable {{ repo_name }} repo
  sudo: True
  copy:
    dest: /etc/yum.repos.d/{{ repo_name }}.repo
    content: "{{ repo_file_content }}"
    mode: 0644
  register: repo_file

- name: Add {{ repo_name }} repo key
  sudo: True
  rpm_key: state=present key={{ repo_key_url }}

- name: Install {{ repo_name }} packages
  sudo: True
  dnf: name={{ item }} state=installed
  with_items: packages
