unity_gsettings:
  com.canonical.Unity.Lenses.remote-content-search: "'none'"
  com.canonical.indicator.datetime.show-date: "true"
  org.gnome.desktop.wm.keybindings.activate-window-menu: "['<Primary><Alt>space']"
  org.gnome.desktop.wm.preferences.mouse-button-modifier: "'<Super>'"
  org.gnome.desktop.wm.preferences.resize-with-right-button: "true"
  org.gnome.desktop.input-sources.xkb-options: "['caps:none']"
  org.compiz.integrated.show-hud: "['<Alt>space']"

# keys that are not present in a gsetting schema can be created with dconf directly
unity_dconf:
  /org/compiz/profiles/unity/plugins/unityshell/shortcut-overlay: "false"
  /org/compiz/profiles/unity/plugins/unityshell/disable-show-desktop: "true"
  /org/compiz/profiles/unity/plugins/unityshell/background-color: "'#212121ff'"
  /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode: "1"
  /org/compiz/profiles/unity/plugins/unityshell/launcher-opacity: "0.75"
  /org/compiz/profiles/unity/plugins/unityshell/alt-tab-timeout: "false"
  /org/compiz/profiles/unity/plugins/core/hsize: "1"
  /org/compiz/profiles/unity/plugins/core/vsize: "3"
