dependencies:
  - role: source/ubuntu/extra_repo
    repo_name: google-chrome
    packages: google-chrome-stable
    repo_key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    repo_file_content: |
        deb http://dl.google.com/linux/chrome/deb/ stable main

    when: ansible_distribution == "Ubuntu"

  - role: source/fedora/extra_repo
    repo_name: google-chrome
    packages: google-chrome-stable
    repo_key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    repo_file_content: |
        [google-chrome]
        name=google-chrome - \$basearch
        baseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch
        enabled=1
        gpgcheck=1
        gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
        
    when: ansible_distribution == "Fedora"
