- name: Check if Flash plugin is installed
  command: rpm --quiet --query flash-plugin
  failed_when: false
  changed_when: flash_installed.rc != 0
  register: flash_installed

- name: Enables Flash repo
  script: install-flash.sh
  when: flash_installed.rc != 0

- name: Install Flash package
  dnf: name=flash-plugin state=present
