- name: Check if mbpfan is installed
  stat: path=/usr/sbin/mbpfan
  register: mbpfan_binary

- name: Unpack archive
  unarchive: src={{ archive_path }} dest=/tmp copy=no
  when: |
    not ( mbpfan_binary.stat.exists
          and mbpfan_binary.stat.islnk
          and mbpfan_binary.stat.lnk_source is defined
          and mbpfan_binary.stat.lnk_source == "/usr/sbin/mbpfan-{{ version }}" )

- name: Copy binary
  command: cp /tmp/mbpfan/bin/mbpfan /usr/sbin/mbpfan-{{ version }}
  args:
    creates: /usr/sbin/mbpfan-{{ version }}

- name: Link binary
  file:
    state: link
    src: /usr/sbin/mbpfan-{{ version }}
    dest: /usr/sbin/mbpfan
  notify: restart mbpfan.service

- name: Copy configuration
  copy: src=mbpfan.conf dest=/etc/mbpfan.conf
  notify: restart mbpfan.service

- name: Test setup
  command: /usr/sbin/mbpfan -t
  changed_when: False

- name: Install mbpfan.service
  command: cp /tmp/mbpfan/mbpfan.service /usr/lib/systemd/system/
  args:
    creates: /usr/lib/systemd/system/mbpfan.service
  notify: restart mbpfan.service
  when: ansible_distribution == "Fedora"

- name: Install mbpfan.service
  command: cp /tmp/mbpfan/mbpfan.upstart /etc/init/mbpfan.conf
  args:
    creates: /etc/init/mbpfan.conf
  notify: restart mbpfan.service
  when: ansible_distribution == "Ubuntu"

- meta: flush_handlers

- name: Start and enable mbpfan.service
  service: name=mbpfan enabled=true state=started
