- name: Override default ntp servers in systemd-timesyncd
  template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
  when: ntp_servers is defined
  notify: restart timesyncd

- meta: flush_handlers

- name: Enable and start systemd-timesyncd
  service: name=systemd-timesyncd state=started enabled=true
