- name: Configure unity gsettings
  gsetting:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: unity_gsettings

- name: Configure unity dconf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: unity_dconf
