- name: Define modprobe.d config file for Apple keyboard Fn key swap
  copy: src=hid-apple.conf dest=/etc/modprobe.d/hid-apple.conf
  register: hid_apple

- name: Add kernel boot parameters to enable Fn key swap
  command: sudo update-initramfs -u -k all
  when: hid_apple.changed

