nautilus_gsettings:
  org.gnome.nautilus.preferences.default-folder-viewer: "'list-view'"
  org.gnome.nautilus.preferences.sort-directories-first: "true"
  org.gnome.nautilus.list-view.use-tree-view: "true"
