dependencies:
  - { role: source/fedora/fedy, targets: sublime_text3, when: ansible_distribution == "Fedora" }
  - { role: source/ubuntu/ppa, ppa: "ppa:webupd8team/sublime-text-3", packages: sublime-text-installer, when: ansible_distribution == "Ubuntu" }

