- name: Check if fedy is already installed
  stat: path=/etc/yum.repos.d/fedy.repo
  register: fedy_repo
  changed_when: false

- name: Puts fedy installer in place
  copy: src=fedy-installer dest=/tmp/fedy-installer mode=755
  when: fedy_repo.stat.exists is defined and not fedy_repo.stat.exists

- name: Runs fedy installer
  command: /tmp/fedy-installer
  when: fedy_repo.stat.exists is defined and not fedy_repo.stat.exists

- name: Runs fedy targets
  command: fedy -e {{ item }}
  with_items: targets
