- name: Check if fedy is already installed
  stat: path=/etc/yum.repos.d/fedy.repo
  sudo: True
  register: fedy_repo
  changed_when: False

- name: Puts fedy installer in place
  copy: src=fedy-installer dest=/tmp/fedy-installer mode=755
  sudo: True
  when: fedy_repo.stat.exists is defined and not fedy_repo.stat.exists

- name: Runs fedy installer
  command: /tmp/fedy-installer
  sudo: True
  when: fedy_repo.stat.exists is defined and not fedy_repo.stat.exists

- name: Runs fedy targets
  command: fedy -e {{ item }}
  sudo: True
  with_items: targets
  when: targets is defined
