- name: Hardware setup - Fedora/MBP
  hosts: "os_Fedora_21:&hardware_MacBookPro11,1"
  sudo: yes
  roles:
    - mbp-hardware/fedora/power-management
    - mbp-hardware/all/boot
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/wireless

- name: Shell setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedy
      targets:
        - color_prompt
        - disk_io_scheduler
    - role: source/fedora/fedora_repos
      packages:
        - autojump
        - ranger

- name: Gnome3 setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedy
      targets:
        - font_rendering
        - media_codecs
        # - dvd_playback
        - adobe_flash
        - elegance_colors
        - numix_themes

- name: Application setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedora_repos
      packages:
        - gitg
    - role: source/fedora/fedy
      targets:
        - sublime_text3

