#! /usr/bin/env sh
# From comments to http://jimhoskins.com/2013/07/27/remove-untagged-docker-images.html
echo "Deleting the following images:"
docker images -q --filter "dangling=true"
docker images -q --filter "dangling=true" | xargs docker rmi
