- name: Checks if copr repository {{ user }}/{{ project }} is installed
  stat: path=/etc/yum.repos.d/_copr_{{ user }}-{{ project }}.repo
  sudo: True
  register: repo_file

- name: Installs dnf-plugins-core
  dnf: name=dnf-plugins-core state=present
  sudo: True
  when: repo_file.stat.exists is defined and not repo_file.stat.exists

- name: Installs copr repository {{ user }}/{{ project }}
  command: dnf copr enable -y {{ user }}/{{ project }}
  sudo: True
  when: repo_file.stat.exists is defined and not repo_file.stat.exists

- name: Installs packages from copr repo, if supplied
  dnf: name={{ item }} state=present
  sudo: True
  with_items: packages
  when: packages is defined
