- name: Create go base path
  file:
    state: directory
    path: "{{ ansible_env['HOME'] }}/Code/go"

- name: Set GOPATH environment variable
  copy:
    src: golang.sh
    dest: "{{ ansible_env['HOME'] }}/.environment.d/"
    mode: 0755
