#!/bin/bash

# Script to install Fedy <http://satya164.github.io/fedy/>.
# Copyright (C) 2014  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


echo "Adding repositories..."
rpm --quiet --query ozon-repos || dnf -y --nogpgcheck install http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm


echo "Installing fedy..."

dnf -y --nogpgcheck install fedy

# Please report bugs at <http://github.com/satya164/fedy/issues>
# End of the Script
