#!/bin/bash

# Script to install Fedy <http://satya164.github.io/fedy/>.
# Copyright (C) 2014  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


echo "Adding repositories..."
rpm --quiet --query ozon-repos || dnf -y --nogpgcheck install http://goodies.ozon-os.com/repo/$(rpm -E %fedora)/noarch/ozon-repos-$(rpm -E %fedora)-5.fc$(rpm -E %fedora).noarch.rpm

echo "Installing fedy..."

dnf -y --nogpgcheck install fedy

# Please report bugs at <http://github.com/satya164/fedy/issues>
# End of the Script
