dependencies:
  - role: source/all/repo
    packages: gtk-murrine-engine

  - role: source/fedora/copr
    user: satya164
    project: numix
    packages:
      - numix-gtk-theme
      - numix-icon-theme
      - numix-icon-theme-circle
    when: ansible_distribution == "Fedora"
