- name: Enable {{ repo_name }} repo
  copy:
    dest: /etc/yum.repos.d/{{ repo_name }}.repo
    content: "{{ repo_file_content }}"
    mode: 775
  register: repo_file

- name: Add {{ repo_name }} repo key
  command: rpm --import {{ repo_key_url }}
  when: repo_file.changed

- name: Install {{ repo_name }} packages
  yum: name={{ item }} state=installed
  with_items: packages
