- name: Create config folder
  file: state=directory name={{ ansible_env['HOME'] }}/.config/terminator

- name: Copy config file
  template: src=config dest={{ ansible_env['HOME'] }}/.config/terminator/config
