# Check wakeups with `cat /proc/acpi/wakeup`

# Disables wakeups form xhc/lid
- name: Instate udev rule to prevent xhc/lid wakeups that prevent suspend
  copy: src=90-xhc_lid_sleep.rules dest=/etc/udev/rules.d/

# TODO: remove later
- name: Remove old udev rules file
  file: state=absent path=/etc/udev/rules.d/90-xhc_sleep.rules
- name: Disables old systemd service
  service: state=stopped enabled=false name=disable-lid0-wakeup.service
  when: ansible_distribution == "Fedora"
- name: Remove old systemd service
  file: state=absent path=/usr/lib/systemd/system/disable-lid0-wakeup.service
- name: Remove old systemd service
  file: state=absent path=/etc/systemd/system/multi-user.target.wants/disable-lid0-wakeup.service
