# `fc-cache -f -v` seems to be unnecessary, could it be that systemd takes care of this?

- name: Creates fonts folder
  file: state=directory name=/usr/local/share/fonts

- name: Installs fonts
  copy: src="{{ font_source_path }}/" dest=/usr/local/share/fonts/
