# Fix interrupt gpe66 hogging CPU
- name: Define disable-gpe66.service
  copy: src=disable-gpe66.service dest=/usr/lib/systemd/system/
  notify: restart disable-gpe66.service

- meta: flush_handlers

- name: Start and enable disable-gpe.service
  service: name=disable-gpe66.service enabled=true state=started
