# Check wakeups with `cat /proc/acpi/wakeup`

# Disables wakeups form xhc
- name: Instate udev rule to prevent xhc wakeups that prevent suspend
  copy: src=90-xhc_sleep.rules dest=/etc/udev/rules.d/

# Disables wakeups from lid0
- name: Define disable-lid0-wakeup.service
  copy: src=disable-lid0-wakeup.service dest=/usr/lib/systemd/system/
  notify: restart disable-lid0-wakeup.service

- meta: flush_handlers

- name: Start and enable disable-lid0-wakeup.service
  service: name=disable-lid0-wakeup.service enabled=true state=started
