- name: Add Oracle JDK repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept Oracle JDK license
  debconf:
    name: "oracle-java8-installer"
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle JDK package
  apt: pkg=oracle-java8-installer state=present

- name: Set JAVA_HOME environment variable
  lineinfile:
    dest: /etc/environment
    line: JAVA_HOME=/usr/lib/jvm/java-8-oracle
