gnome_shell_enabled_extensions:
  - user-theme@gnome-shell-extensions.gcampax.github.com
  - impatience@gfxmonk.net
  - topIcons@adel.gadllah@gmail.com
  - battery_status@milliburn.github.com
  - GPaste@gnome-shell-extensions.gnome.org
  - dash-to-dock@micxgx.gmail.com
