- name: Create Elegance colors config folder
  file: state=directory dest={{ ansible_env["HOME"] }}/.config/elegance-colors mode=755

- name: Install Elegance colors theme file
  copy: src=elegance-colors.ini dest={{ ansible_env["HOME"] }}/.config/elegance-colors/elegance-colors.ini mode=644

- name: Configure gnome gsettings
  gsetting:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: gnome_gsettings
