- name: install macfanctl
  apt: name={{ item }} state=latest
  with_items:
    - macfanctld

- name: install tlp power management
  apt_repository: repo='ppa:linrunner/tlp'
- apt: name={{ item }} state=latest
  with_items:
    - tlp
    - tlp-rdw

- name: fix interrupt kworker hogging CPU
  copy: src=rc.local dest=/etc/rc.local mode=755
# to find offending interrupts:
# grep . -r /sys/firmware/acpi/interrupts/

- name: Fn key swap
  copy: src=hid-apple.conf dest=/etc/modprobe.d/hid-apple.conf
  register: hid_apple
- command: sudo update-initramfs -u -k all
  when: hid_apple.changed

- name: wifi resume fix
  copy: src=99_wifi-resume-fix dest=/etc/pm/sleep.d/99_wifi-resume-fix mode=755

- name: switch command and option keys
  file: state=directory dest=/opt/keyboard-tweaks
- file: state=touch dest=/opt/keyboard-tweaks/keyboard-tweaks.log mode=666
- copy: src=xmodmap.conf dest=/opt/keyboard-tweaks/xmodmap.conf
- copy: src=keyboard-tweaks dest=/opt/keyboard-tweaks/keyboard-tweaks mode=755
- copy: src=keyboard-tweaks.desktop dest=/etc/xdg/autostart/keyboard-tweaks.desktop
