- name: Activate ppa {{ ppa }}
  sudo: yes
  apt_repository: repo="{{ ppa }}" state=present

- name: Install packages {{ packages }}
  apt: name="{{ item }}" state=present
  sudo: yes
  with_items: packages
