- name: Boostrap setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: base/all/nas
      tags: nas
    - base/fedora/dnf
    - base/fedora/rpmfusion
  tags: base

# - Hardware -----------------------------------

- name: Hardware setup - Fedora/MBP 11,1
  hosts: "os_Fedora_21:&hardware_MacBookPro11,1"
  sudo: yes
  roles:
    - mbp-hardware/all/mbpfan
    - mbp-hardware/fedora/interrupt-fix
    - { role: source/all/repo, packages: ["tlp", "tlp-rdw"] }
    - mbp-hardware/all/boot
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/wireless
    - mbp-hardware/fedora/suspend-fix
    - mbp-hardware/all/colour-profile
  tags:
    - base
    - hardware

- name: Hardware setup - Fedora/MBP 12,1
  hosts: "os_Fedora_21:&hardware_MacBookPro12,1"
  sudo: yes
  roles:
    - mbp-hardware/all/mbpfan
    - { role: source/all/repo, packages: ["tlp", "tlp-rdw"] }
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/suspend-fix
    - mbp-hardware/all/colour-profile
  tags:
    - base
    - hardware

- name: Hardware setup - Peripherials - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: peripherial-hardware/fedora/roccat-kovaplus
      when: |
          peripherial_hardware is defined
          and 'roccat-kovaplus' in peripherial_hardware
  tags: hardware

# - Base ---------------------------------------

- name: Shell setup user specific - Fedora
  hosts: os_Fedora_21
  sudo: no
  roles:
    - role: shell/all/bashrc
    - shell/all/autojump
  tags:
    - shell
    - user-specific

- name: Shell setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - vim
        - ranger
    - shell/fedora/colour-prompt
    - shell/fedora/sudo
    - shell/all/toolbox
  tags:
    - shell

- name: Base setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: base/fedora/ntp
    - role: source/all/repo
      packages:
        - openvpn
        - sshpass
        # needed for ldd to digest 32bit binaries
        - glibc.i686
        - icedtea-web
    - base/fedora/ssd-scheduler
    - base/fedora/freetype
    - role: base/all/fonts
      tags: nas
    - base/fedora/flash
    - base/fedora/codecs
    - base/fedora/selinux
    - base/all/oracle-jdk
    - base/fedora/airvpn
  tags: base

# - Desktop --------------------------------------

- name: Gnome3 setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - gnome-tweak-tool
        - dconf-editor
        - gnome-shell-extension-gpaste
        - gnome-logs
    - gnome/fedora/numix
    - gnome/fedora/elegance_colors
    - gnome/all/spellcheck
    - gnome/all/power-commands
  tags: gnome

- name: Gnome3 setup user specific - Fedora
  hosts: os_Fedora_21
  sudo: no
  roles:
    - role: gnome/all/gvfs-mount
      tags: nas
    - gnome/all/directories
    - role: gnome/all/data
      tags: nas
    - gnome/all/shell-extensions
    - gnome/all/shell
    - gnome/all/nautilus
  tags:
    - gnome
    - user-specific

# - Apps ---------------------------------------

- name: Application setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - apps/all/passwordmaker
    - apps/all/chrome
    - apps/all/scudcloud
    - role: source/all/repo
      packages:
        - gparted
        - gitg
        - geary
        - california
        - gnome-maps
        - antimicro
        - tomahawk
        - vlc
        - shutter
  tags: apps

- name: Application setup user specific - Fedora
  hosts: os_Fedora_21
  sudo: no
  roles:
    - apps/all/terminator
    - role: apps/all/sublime-text-3
      tags:
        - update
        - sublime
    - role: apps/all/net-id
      when: |
        optional_apps is defined
        and 'net-id' in optional_apps
  tags:
    - apps
    - user-specific

# - Development --------------------------------

- include: fedora-development.yaml
