- name: Boostrap setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - base/all/nas
    - base/fedora/yum
    - base/fedora/rpmfusion
  tags: base

# - Hardware -----------------------------------

- name: Hardware setup - Fedora/MBP 11,1
  hosts: "os_Fedora_21:&hardware_MacBookPro11,1"
  sudo: yes
  roles:
    - mbp-hardware/fedora/interrupt-fix
    - mbp-hardware/fedora/mbpfan
    - { role: source/all/repo, packages: ["tlp", "tlp-rdw"] }
    - mbp-hardware/all/boot
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/wireless
    - mbp-hardware/fedora/suspend-fix
    - mbp-hardware/all/colour-profile
  tags:
    - base
    - hardware

- name: Hardware setup - Fedora/MBP 12,1
  hosts: "os_Fedora_21:&hardware_MacBookPro12,1"
  sudo: yes
  roles:
    - mbp-hardware/fedora/mbpfan
    - { role: source/all/repo, packages: ["tlp", "tlp-rdw"] }
    - mbp-hardware/fedora/keyboard
    - mbp-hardware/fedora/suspend-fix
    - mbp-hardware/all/colour-profile
  tags:
    - base
    - hardware

# - Base ---------------------------------------

- name: Base setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedy
      targets:
        - disk_io_scheduler
        - font_rendering
        - media_codecs
        - adobe_flash
        # - dvd_playback
    - role: source/all/repo
      packages:
        - openvpn
    - base/all/fonts
  tags: base

- name: Shell setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedy
      targets:
        - color_prompt
    - role: source/all/repo
      packages:
        - vim
        - autojump
        - ranger
  tags: shell

# - Desktop --------------------------------------

- name: Gnome3 setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/fedora/fedy
      targets:
        - elegance_colors
        - numix_themes
    - role: source/all/repo
      packages:
        - gnome-tweak-tool
        - dconf-editor
        - gnome-shell-extension-gpaste
    - gnome/all/spellcheck
    - gnome/all/power-commands
  tags: gnome

- name: Gnome3 setup user specific - Fedora
  hosts: os_Fedora_21
  sudo: no
  roles:
    - gnome/all/gvfs-mount
    - gnome/all/directories
    - gnome/all/data
    - gnome/all/shell
    - gnome/all/nautilus
  tags:
    - gnome
    - user-specific

# - Apps ---------------------------------------

- name: Application setup - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - apps/all/passwordmaker
    - role: source/all/repo
      packages:
        - gparted
        - gitg
        - geary
        - california
        - antimicro
        - tomahawk
        - vlc
    - role: apps/fedora/chrome
  tags: apps

- name: Application setup user specific - Fedora
  hosts: os_Fedora_21
  sudo: no
  roles:
    - apps/all/terminator
    - apps/all/sublime-text-3
  tags:
    - apps
    - user-specific

- name: Development setup - Common - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - development/fedora/vagrant
    - role: source/all/repo
      packages:
        - meld
        - android-tools
  tags: development

- name: Development setup - Go - Fedora
  hosts: os_Fedora_21
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - golang
        - mercurial
  tags: development
