- name: Boostrap setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - base/all/nas
  tags: base

# - Hardware -----------------------------------

- name: Hardware setup - Ubuntu
  hosts: "os_Ubuntu_14:&hardware_MacBookPro11,1"
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes cache_valid_time=360
  roles:
    - role: mbp-hardware/all/mbpfan
    - mbp-hardware/ubuntu/interrupt-fix
    - role: source/ubuntu/ppa
      ppa: "ppa:linrunner/tlp"
      packages: ["tlp", "tlp-rdw"]
    - mbp-hardware/ubuntu/wifi-resume-fix
    - mbp-hardware/ubuntu/keyboard
    - mbp-hardware/all/boot
    - mbp-hardware/all/colour-profile

# - Base ---------------------------------------

- name: Base setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/ubuntu/ppa
      ppa: ppa:mc3man/trusty-media
      packages:
        - ffmpeg
        - gstreamer0.10-ffmpeg
    - role: source/all/repo
      packages:
        - ubuntu-restricted-extras
        - openvpn
    - base/all/fonts
    - base/all/oracle-jdk
  tags: base

- name: Shell setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - vim
        - ranger
    - role: shell/ubuntu/bashrc
      sudo: no
    - shell/all/autojump
    - shell/all/toolbox
  tags:
    - shell
    - user-specific

# - Desktop --------------------------------------

- name: Unity setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - unity-tweak-tool
        - gnome-tweak-tool
        - dconf-editor
        - clipit
    - gnome/all/spellcheck
  tags:
    - gnome
    - unity

- name: Gnome3 setup user specific - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - gnome/all/gvfs-mount
    - gnome/all/directories
    - gnome/all/data
    - unity/ubuntu/dash
    - gnome/all/nautilus
    - unity/ubuntu/synapse
  tags:
    - gnome
    - unity
    - user-specific

# - Apps ---------------------------------------

- name: Application setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - apps/all/passwordmaker
    - apps/all/chrome
    - apps/all/scudcloud
    - { role: source/ubuntu/ppa, ppa: "ppa:yorba/ppa", packages: geary }
    - role: source/all/repo
      packages:
        - gparted
        - gitg
        - tomahawk
        - vlc
        - shutter
  tags: apps

- name: Application setup user specific - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - apps/all/terminator
    - { role: apps/all/sublime-text-3, tags: update }
  tags:
    - apps
    - user-specific

- name: Development setup - Common - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    # - development/fedora/vagrant
    - development/all/android
    - role: source/all/repo
      packages:
        - meld
  tags: development

- name: Gaming setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/ubuntu/ppa
      ppa: "ppa:ryochan7/antimicro"
      packages: antimicro
    - role: source/ubuntu/ppa
      ppa: "ppa:falk-t-j/qtsixa"
      packages: qtsixa
    - role: source/ubuntu/ppa
      ppa: "ppa:guilhem-fr/performous-daily"
      packages: performous
    - role: source/ubuntu/ppa
      ppa: "ppa:tobydox/ultrastardx"
      packages: ultrastar-deluxe
    # TODO: Automate steam installation
    #   (when license acceptance via debconf is fixed)
    - role: source/ubuntu/ppa
      ppa: "ppa:minecraft-installer-peeps/minecraft-installer"
      packages: minecraft-installer
  tags: games
