- name: Boostrap setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: base/all/nas
      tags: nas
  tags: base

# - Hardware -----------------------------------

- name: Hardware setup - Ubuntu
  hosts: "os_Ubuntu_14:&hardware_MacBookPro11,1"
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes cache_valid_time=360
  roles:
    - role: mbp-hardware/all/mbpfan
    - mbp-hardware/ubuntu/interrupt-fix
    - role: source/ubuntu/ppa
      ppa: "ppa:linrunner/tlp"
      packages: ["tlp", "tlp-rdw"]
    - mbp-hardware/ubuntu/wifi-resume-fix
    - mbp-hardware/ubuntu/keyboard
    - mbp-hardware/all/boot
    - mbp-hardware/all/colour-profile
  tags:
    - base
    - hardware

- name: Hardware setup - Peripherials - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - role: peripherial-hardware/all/roccat-kovaplus
      when: |
          peripherial_hardware is defined
          and 'roccat-kovaplus' in peripherial_hardware
  tags: hardware

# - Base ---------------------------------------

- name: Shell setup user specific - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - role: shell/all/bashrc
    - shell/all/autojump
  tags:
    - shell
    - user-specific

- name: Shell setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - vim
        - ranger
    - shell/all/toolbox
  tags:
    - shell
    - user-specific

- name: Base setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/ubuntu/ppa
      ppa: ppa:mc3man/trusty-media
      packages:
        - ffmpeg
        - gstreamer0.10-ffmpeg
    - role: source/all/repo
      packages:
        - ubuntu-restricted-extras
        - openvpn
        - sshpass
    - role: base/all/fonts
      tags: nas
    - base/all/oracle-jdk
  tags: base

# - Desktop --------------------------------------

- name: Unity setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - role: source/all/repo
      packages:
        - unity-tweak-tool
        - gnome-tweak-tool
        - dconf-editor
        - clipit
    - gnome/all/spellcheck
  tags:
    - gnome
    - unity

- name: Gnome3 setup user specific - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - role: gnome/all/gvfs-mount
      tags: nas
    - gnome/all/directories
    - role: gnome/all/data
      tags: nas
    - unity/ubuntu/dash
    - gnome/all/nautilus
    - unity/ubuntu/synapse
  tags:
    - gnome
    - unity
    - user-specific

# - Apps ---------------------------------------

- name: Application setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    - apps/all/passwordmaker
    - apps/all/chrome
    - apps/all/scudcloud
    - { role: source/ubuntu/ppa, ppa: "ppa:yorba/ppa", packages: geary }
    - role: source/all/repo
      packages:
        - gparted
        - gitg
        - tomahawk
        - vlc
        - shutter
  tags: apps

- name: Application setup user specific - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - apps/all/terminator
    - role: apps/all/sublime-text-3
      tags:
        - update
        - sublime
  tags:
    - apps
    - user-specific

- name: Development setup - Common - Ubuntu
  hosts: os_Ubuntu_14
  sudo: yes
  roles:
    # - development/fedora/vagrant
    - development/all/android
    - role: source/all/repo
      packages:
        - meld
  tags: development

- name: Gaming setup - Ubuntu
  hosts: os_Ubuntu_14
  sudo: no
  roles:
    - gaming/ubuntu/antimicro
    - gaming/ubuntu/qtsixa
    - role: source/ubuntu/ppa
      ppa: "ppa:guilhem-fr/performous-daily"
      packages: performous
    - role: source/ubuntu/ppa
      ppa: "ppa:tobydox/ultrastardx"
      packages: ultrastar-deluxe
    # TODO: Automate steam installation
    #   (when license acceptance via debconf is fixed)
    - role: source/ubuntu/ppa
      ppa: "ppa:minecraft-installer-peeps/minecraft-installer"
      packages: minecraft-installer
  tags: gaming
