- name: Install docker package
  dnf: name=docker state=present

- name: Start and enable docker daemon
  service: name=docker state=started enabled=True

- name: Add user to docker group
  user: name={{ ansible_env['USER'] }} state=present groups=docker append=True
