- name: Install docker package
  dnf: name=docker state=present

- name: Start and enable docker daemon
  service: name=docker state=started enabled=True

- name: Removes docker group
  group: name=docker state=absent
